wip snapshot

diff --git a/bin/build-lumen b/bin/build-lumen
--- a/bin/build-lumen
+++ b/bin/build-lumen
@@ -10,7 +10,7 @@ OUTPUT_DIR="${ROOT_DIR}/target/debug"
 RUSTC_PATH="$(rustup which --toolchain nightly rustc)"
 TOOLCHAIN_BIN_PATH="$(cd "$(dirname "$RUSTC_PATH")" && pwd -P)"
 TOOLCHAIN_LIB_PATH="$(cd "$TOOLCHAIN_BIN_PATH"/../lib && pwd -P)"
-RUNTIME_LIBS=(liblumen_core liblumen_crt liblumen_alloc lumen_rt_minimal)
+RUNTIME_LIBS=(liblumen_core liblumen_crt liblumen_alloc lumen_rt_core lumen_rt_minimal)
 
 export LLVM_SYS_90_PREFIX
 LLVM_SYS_90_PREFIX="${LLVM_SYS_90_PREFIX}"
@@ -25,18 +25,12 @@ build_dynamic="false"
 build_use_libcxx="false"
 build_link_args=""
 build_runtimes=""
+build_package=""
+build_target=""
+build_toolchain=""
+host_target=""
 extra_rustc_flags=""
 extra_cargo_flags=""
-host_target=""
-if ! host_target="$(rustup toolchain list | grep 'default' | sed -e 's/nightly-//' -e 's/ (default)//')"; then
-    echo "Unable to determine default host toolchain!"
-    exit 2
-fi
-if [[ "$host_target" =~ "apple-darwin" ]]; then
-    is_darwin="true"
-fi
-build_target="$host_target"
-install_prefix="${BIN_DIR}/${host_target}"
 
 function usage() {
     echo "usage: $(basename "$0") [--static] [OPTIONS..]"
@@ -49,6 +43,7 @@ function usage() {
     echo " --use-libcxx         Build the compiler dynamically linked against its libraries"
     echo " --target <triple>    The target triple to build for"
     echo " --install <prefix>   Install to the given prefix"
+    echo " --package <package>  Build a specific crate (i.e. like cargo -p)"
     echo ""
 }
 
@@ -104,6 +99,12 @@ while [ $# -gt 0 ]; do
         -target | --target )
             has_value="true"
             build_target="$rhs"
+            build_toolchain="$build_target"
+            ;;
+
+        -package | --package )
+            has_value="true"
+            build_package="$rhs"
             ;;
 
         *)
@@ -121,18 +122,53 @@ while [ $# -gt 0 ]; do
     fi
 done
 
-TOOLCHAIN_TARGET_PATH="${TOOLCHAIN_LIB_PATH}/rustlib/${build_target}"
+if ! type -p jq >/dev/null; then
+    echo "Expected jq to be on your PATH"
+    exit 2
+fi
+
+if ! host_toolchain="$(rustup toolchain list | grep 'default' | sed -e 's/nightly-//' -e 's/ (default)//')"; then
+    echo "Unable to determine default host toolchain!"
+    exit 2
+fi
+if [ -z "$build_target" ]; then
+    if ! host_target="$(rustc -Z unstable-options --print target-spec-json | jq -r '."llvm-target"')"; then
+        echo "Failed to load target spec!"
+        exit 2
+    fi
+    # On macOS, the toolchain and target triple are mismatched
+    if [[ "$host_target" =~ "apple-" ]]; then
+        is_darwin="true"
+        build_target="$host_target"
+        build_toolchain="$host_toolchain"
+    else
+        build_target="$host_target"
+        build_toolchain="$host_target"
+    fi
+else
+    # shellcheck disable=SC2086
+    if ! host_target="$(rustc -Z unstable-options --target ${build_target} --print target-spec-json | jq -r '."llvm-target"')"; then
+        echo "Failed to load target spec!"
+        exit 2
+    fi
+    if [[ "$host_target" =~ "apple-" ]]; then
+        is_darwin="true"
+    fi
+fi
+install_prefix="${BIN_DIR}/${host_target}"
+
+TOOLCHAIN_TARGET_PATH="${TOOLCHAIN_LIB_PATH}/rustlib/${build_toolchain}"
 if [ -d "${TOOLCHAIN_TARGET_PATH}" ]; then
     TOOLCHAIN_TARGET_LIB_PATH="${TOOLCHAIN_TARGET_PATH}/lib"
 else
-    echo "Unable to find toolchain for target ($build_target):"
+    echo "Unable to find toolchain for target ($build_toolchain):"
     echo "  ${TOOLCHAIN_TARGET_PATH} not found"
     echo ""
     exit 2
 fi
-if [ "$host_target" != "$build_target" ]; then
+if [ "$host_toolchain" != "$build_toolchain" ]; then
     is_crossed="true"
-    extra_cargo_flags="$extra_cargo_flags --target $build_target"
+    extra_cargo_flags="$extra_cargo_flags --target $build_toolchain"
 else
     is_crossed="false"
 fi
@@ -154,6 +190,7 @@ cd "$ROOT_DIR"
 echo "Building Lumen"
 echo "  host:                $host_target"
 echo "  target:              $build_target"
+echo "  toolchain:           $build_toolchain"
 echo "  is cross compile:    $is_crossed"
 echo "  build static:        $build_static"
 echo "  build w/ libc++:     $build_use_libcxx"
@@ -161,6 +198,15 @@ echo "  extra rustc flags:   ${extra_rustc_flags:-"n/a"}"
 echo "  extra cargo flags:   ${extra_cargo_flags:-"n/a"}"
 echo "  extra link args:     ${build_link_args:-"n/a"}"
 echo ""
+
+function find_static_dep(){
+    # Sort by modification time, and take the first two entries,
+    # these correspond to the build script output, and the build folder itself.
+    find "${OUTPUT_DIR}/deps" -type f -name "lib$1-*.a" -exec stat --printf='%Y\t%n\n' {} \; \
+        | sort -r \
+        | head -n 1 \
+        | cut -f2 -
+}
 
 function build_dep(){
     # shellcheck disable=SC2086
@@ -171,22 +217,39 @@ function build_dep(){
     fi
 }
 
+function build_or_copy_dep(){
+    local lib="$1"
+    local lib_path=""
+    local to_path="$2"
+    if ! lib_path="$(find_static_dep "$lib")"; then
+        # Build this library
+        if ! build_dep "$lib"; then
+            echo "Failed to build runtime library '$lib'"
+            return 1
+        fi
+        if ! lib_path="$(find_static_dep "$lib")"; then
+            echo "Unable to find static library '$lib'"
+            return 1
+        fi
+    fi
+    if [ ! -f "$lib_path" ]; then
+        echo "Unable to find static library '$lib' at '$lib_path'"
+        return 1
+    fi
+    rsync -a --copy-links --whole-file "$lib_path" "${to_path}/lib${lib}.a"
+}
+
+if [ -n "$build_package" ]; then
+    # shellcheck disable=SC2086
+    if ! cargo rustc ${extra_cargo_flags} -p ${build_package} -- -C link-args="-Wl,$build_link_args" ${extra_rustc_flags}; then
+        exit 1
+    fi
+    exit 0
+fi
+
 # shellcheck disable=SC2086
 if ! cargo rustc ${extra_cargo_flags} -p lumen -- -C link-args="-Wl,$build_link_args" ${extra_rustc_flags}; then
     exit 1
-fi
-
-# Build runtime libraries which the compiler links executables against
-if [ -n "$build_runtimes" ]; then
-    echo ""
-    echo "Building runtime crates.."
-    echo ""
-    for lib in "${RUNTIME_LIBS[@]}"; do
-        if ! build_dep "$lib"; then
-            echo "Failed to build runtime library '$lib'"
-            exit 1
-        fi
-    done
 fi
 
 # Construct install directory
@@ -200,36 +263,33 @@ mkdir -p "${install_host_lib_dir}"
 mkdir -p "${install_target_lib_dir}"
 mkdir -p "${install_prefix}"/{etc,share}
 cp "${OUTPUT_DIR}/lumen" "${install_bin_dir}/lumen"
-if [ "$build_dynamic" == "true" ]; then
-    src_dylib="${LLVM_SYS_90_PREFIX}/lib/libLLVMcpp.dylib"
-    if [ -f "${src_dylib}" ]; then
-        # We have a components dylib, so prefer to use that
-        dst_dylib="${install_host_lib_dir}/libLLVMcpp.dylib"
-        rsync -a --copy-links --whole-file "$src_dylib" "$dst_dylib"
-    else
-        # Otherwise we must have built with BUILD_SHARED_LIBS
-        rsync -a --copy-links --whole-file "${LLVM_SYS_90_PREFIX}/lib/"libLLVM*.dylib "${install_host_lib_dir}"/
-        rsync -a --copy-links --whole-file "${LLVM_SYS_90_PREFIX}/lib/"libMLIR*.dylib "${install_host_lib_dir}"/
-    fi
-fi
 
-# Copy runtime libraries
-deps_dir="${OUTPUT_DIR}/deps"
+# Copy runtime libraries, build them if not present
 for lib in "${RUNTIME_LIBS[@]}"; do
-    for file in "$deps_dir/lib$lib"-*.a; do
-        if [ -f "$file" ]; then
-            rsync -a --copy-links --whole-file "$file" "${install_target_lib_dir}/lib${lib}.a"
-        else
-            echo "WARN: Unable to copy $lib! Static library not found."
-        fi
-    done
+    if ! build_or_copy_dep "$lib" "$install_target_lib_dir"; then
+        exit 1
+    fi
 done
+
+#if [ "$build_dynamic" == "true" ]; then
+#    src_dylib="${}"
+#    src_dylib="${LLVM_SYS_90_PREFIX}/lib/libLLVMcpp.dylib"
+#    if [ -f "${src_dylib}" ]; then
+#        # We have a components dylib, so prefer to use that
+#        dst_dylib="${install_host_lib_dir}/libLLVMcpp.dylib"
+#        rsync -a --copy-links --whole-file "$src_dylib" "$dst_dylib"
+#    else
+#        # Otherwise we must have built with BUILD_SHARED_LIBS
+#        rsync -a --copy-links --whole-file "${LLVM_SYS_90_PREFIX}/lib/"libLLVM*.dylib "${install_host_lib_dir}"/
+#        rsync -a --copy-links --whole-file "${LLVM_SYS_90_PREFIX}/lib/"libMLIR*.dylib "${install_host_lib_dir}"/
+#    fi
+#fi
 
 function get_build_dirs(){
     # Sort by modification time, and take the first two entries,
     # these correspond to the build script output, and the build folder itself.
     find "${OUTPUT_DIR}/build" -type d -name "$1-*" -exec stat --printf='%Y\t%n\n' {} \; \
-        | sort \
+        | sort -r \
         | head -n 2 \
         | cut -f2 -
 }
@@ -246,6 +306,7 @@ function get_build_dir(){
     done
     return 1
 }
+
 
 # Copy codegen libraries that are not statically linked
 codegen_out_dir="$(get_build_dir 'liblumen_codegen')"
