fix: cargo build without make for editor support

diff --git a/bin/build-lumen b/bin/build-lumen
--- a/bin/build-lumen
+++ b/bin/build-lumen
@@ -31,6 +31,7 @@ build_link_args=""
 build_package=""
 build_target=""
 build_toolchain=""
+lumen_install_prefix=""
 host_target=""
 extra_rustc_flags=""
 extra_cargo_flags=""
@@ -115,12 +116,16 @@ while [ $# -gt 0 ]; do
             extra_cargo_flags="--verbose $extra_cargo_flags"
             ;;
         -debug | --debug )
-            extra_rustc_flags="-C opt-level=0"
+            extra_rustc_flags="-C opt-level=0 $extra_rustc_flags"
             OUTPUT_DIR="${TARGET_DIR}/debug"
             ;;
 
         -only-tblgen | --only-tblgen )
             only_tblgen="true"
+            ;;
+
+        -install | --install )
+            lumen_install_prefix="$rhs"
             ;;
 
         -release | --release )
@@ -131,6 +136,7 @@ while [ $# -gt 0 ]; do
         -static | --static )
             build_static="true"
             build_dynamic="false"
+            extra_rustc_flags="-C prefer-dynamic=no $extra_rustc_flags"
             ;;
 
         -dynamic | --dynamic )
@@ -163,9 +169,11 @@ while [ $# -gt 0 ]; do
             ;;
 
         *)
-            echo "unknown option: $1"
-            usage
-            exit 2
+            if [ -n "$1" ]; then
+                echo "unknown option: $1"
+                usage
+                exit 2
+            fi
             ;;
     esac
 
@@ -191,6 +199,7 @@ if ! type -p cmake >/dev/null; then
     exit 2
 fi
 
+# shellcheck disable=SC2001
 if ! host_toolchain="$(echo "$RUST_TOOLCHAIN" | sed -e 's/nightly-\([0-9]\{4,4\}-[0-9]\{2,2\}-[0-9]\{2,2\}-\)\{0,1\}//')"; then
     echo "Unable to determine default host toolchain!"
     exit 2
@@ -219,7 +228,7 @@ else
         is_darwin="true"
     fi
 fi
-install_prefix="${BIN_DIR}/${host_target}"
+lumen_install_prefix="${lumen_install_prefix:-${BIN_DIR}/${host_target}}"
 
 TOOLCHAIN_TARGET_PATH="${TOOLCHAIN_LIB_PATH}/rustlib/${build_toolchain}"
 if [ -d "${TOOLCHAIN_TARGET_PATH}" ]; then
@@ -263,6 +272,7 @@ echo "  build w/ libc++:     $build_use_libcxx"
 echo "  extra rustc flags:   ${extra_rustc_flags:-"n/a"}"
 echo "  extra cargo flags:   ${extra_cargo_flags:-"n/a"}"
 echo "  extra link args:     ${build_link_args:-"n/a"}"
+echo "  install prefix:      ${lumen_install_prefix:-"n/a"}"
 echo ""
 
 printf "Checking for lumen-tblgen.."
@@ -278,17 +288,20 @@ if [ ! -f "$OUTPUT_DIR/build/lumen_tblgen/bin/lumen-tblgen" ]; then
         _generator="-GNinja"
         _target="lumen-tblgen"
     fi
-    cmake ${_generator} \
+    if cmake ${_generator} \
         -DLUMEN_BUILD_COMPILER=ON \
         -DLUMEN_BUILD_TESTS=OFF \
         -DBUILD_SHARED_LIBS="OFF" \
         -DLLVM_PREFIX="$LLVM_PREFIX" \
         --target "${_target}" \
-        --build "${ROOT_DIR}/compiler/codegen_llvm" && \
-    "$_gen" "$_target"
-
-    if [[ $? -ne 0 ]]; then
-        echo "Failed to build lumen-tblgen!"
+        --build "${ROOT_DIR}/compiler/codegen_llvm"; then
+        if ! "$_gen" "$_target"; then
+            echo "Failed to build lumen-tblgen!"
+            exit 1
+        fi
+    else
+        echo "Failed to configure lumen-tblgen!"
+        exit 1
     fi
 
     if [ ! -f "bin/lumen-tblgen" ]; then
@@ -330,8 +343,8 @@ if [ -n "$run_bloat" ]; then
 fi
 
 # Build Lumen and gather artifact metadata
-# shellcheck disable=SC2086
 build_json=""
+# shellcheck disable=SC2086
 if ! build_json="$(cargo rustc --message-format=json ${extra_cargo_flags} -p lumen -- -C link-args="-Wl,$build_link_args" ${extra_rustc_flags})"; then
     echo "$build_json" | jq -r 'select(.reason == "compiler-message") | { message: .message.rendered, level: .message.level } | select(.level == "error") | .message'
     exit 1
@@ -355,14 +368,14 @@ fi
 
 # Construct install directory
 echo ""
-echo "Installing Lumen to ${install_prefix}.."
-install_bin_dir="${install_prefix}/bin"
-install_host_lib_dir="${install_prefix}/lib"
-install_target_lib_dir="${install_prefix}/lib/lumenlib/${build_target}/lib"
+echo "Installing Lumen to ${lumen_install_prefix}.."
+install_bin_dir="${lumen_install_prefix}/bin"
+install_host_lib_dir="${lumen_install_prefix}/lib"
+install_target_lib_dir="${lumen_install_prefix}/lib/lumenlib/${build_target}/lib"
 mkdir -p "${install_bin_dir}"
 mkdir -p "${install_host_lib_dir}"
 mkdir -p "${install_target_lib_dir}"
-mkdir -p "${install_prefix}"/{etc,share}
+mkdir -p "${lumen_install_prefix}"/{etc,share}
 cp "${OUTPUT_DIR}/lumen" "${install_bin_dir}/lumen"
 
 # Remove old libraries
@@ -388,11 +401,11 @@ for rustlib in "${rustlibs[@]}"; do
 done
 
 for lib in "${RUNTIME_LIBS[@]}"; do
-    install_library "runtime" $lib
+    install_library "runtime" "$lib"
 done
 
 for lib in "${BIF_LIBS[@]}"; do
-    install_library "BIF" $lib
+    install_library "BIF" "$lib"
 done
 
 # Copy codegen libraries that are not statically linked
@@ -406,7 +419,7 @@ done
 if [ "$is_darwin" = "true" ]; then
     if ! install_name_tool \
             -add_rpath '@executable_path/../lib' \
-            "${install_prefix}/bin/lumen"; then
+            "${lumen_install_prefix}/bin/lumen"; then
         echo "Failed to set Lumen @executable_path!"
         exit 1
     fi
@@ -415,7 +428,7 @@ fi
 echo "Creating symlink.."
 
 cd "${BIN_DIR}"
-ln -sf "${install_prefix}/bin/lumen" lumen
+ln -sf "${lumen_install_prefix}/bin/lumen" lumen
 
 echo "Install complete!"
 
